Panel Working Group
obl-ong/resolutions pull request #2
Opened 2024-03-18 14:30 UTC by reesericci

This PR adds a resolution to form an open committee to oversee v2 development.

2024-03-18 14:33 UTC, aboutdavid requested changes
You didn't spell committee right on line 11, you only had one "t"

2024-03-18 14:34 UTC, reesericci commented
lol mb

2024-03-18 14:43 UTC, aboutdavid approved these changes

2024-04-23 18:48 UTC, reesericci commented
```
OpaVote Election Results (https://www.OpaVote.com/)

Panel WG Resolution

There are 2 candidates competing for 1 seats. The number of voters is 5 and
there were 5 valid votes and 0 empty votes.

Counting votes using Plurality/FPTP/SNTV.

Candidate | Count
=================
      Yes |     3
       No |     2
Exhausted |     0



Winner is Yes.
```

https://www.opavote.com/results/6534249309011968/0

2024-04-23 18:48 UTC, merged